export const SEARCH_MAPPINGS: Record<string, string[]> = {
  "10cm": ["10cm", "십센치", "10센치", "권정열"],
  "2NE1": ["2NE1", "투애니원"],
  가인: ["가인", "송가인"],
  권진아: ["권진아", "진아"],
  김건모: ["김건모", "권모"],
  김영근: ["김영근", "영근"],
  김예림: ["김예림", "예림"],
  김필: ["김필", "필"],
  남규리: ["남규리", "규리"],
  "넬 (NELL)": ["넬", "Nell"],
  "뉴진스 (NJZ)": [
    "뉴진스",
    "newjeans",
    "NJZ",
    "뉴진스 (NJZ)",
    "하니",
    "해린",
    "민지",
    "혜인",
    "다니엘",
  ],
  다비치: ["다비치", "Davichi", "이해리", "강민경"],
  "달의 하루": ["달의 하루", "달의하루"],
  "데이먼스 이어": [
    "데이먼스 이어",
    "데이먼스이어",
    "Daymonsyear",
    "Daymons Year",
  ],
  "데이식스(Day6)": [
    "데이식스",
    "Day6",
    "데이식스 (Day6)",
    "Day6 (데이식스)",
    "데식",
    "영케이",
    "성진",
    "원필",
    "도운",
  ],
  레이나: ["레이나", "Leina"],
  로제: ["로제", "Rosé", "로제 (ROS?)", "Rose"],
  "로제,브루노마스": [
    "로제",
    "브루노마스",
    "로제,브루노마스",
    "Rosé,Bruno Mars",
    "Rose",
    "Bruno Mars",
  ],
  르세라핌: [
    "르세라핌",
    "LE SSERAFIM",
    "LE SSERAFIM (르세라핌)",
    "허윤진",
    "사쿠라",
    "김채원",
    "카즈하",
    "홍은채",
  ],
  리센느: ["리센느", "RESCENE", "원이", "리브", "미나미", "메이", "제나"],
  린: ["린", "LYn"],
  릴러말즈: ["릴러말즈", "Leellamarz"],
  "릴러말즈,TOIL": ["릴러말즈", "토일", "TOIL", "Leellamarz"],
  문문: ["문문", "MoonMoon"],
  미노이: ["미노이", "meenoi"],
  밍기뉴: ["밍기뉴", "Mingginyu"],
  박봄: ["박봄", "Park Bom", "Bom"],
  박원: ["박원", "Park Won"],
  박정현: ["박정현", "Lena Park", "정현"],
  백아: ["백아", "Baek A"],
  백야: ["백야", "BaekYa"],
  백예린: ["백예린", "예린", "yerin", "Baek YeRin"],
  "볼빨간 사춘기": ["볼빨간 사춘기", "볼사", "Bol4", "안지영"],
  블랙핑크: [
    "블랙핑크",
    "BLACKPINK",
    "블핑",
    "BP",
    "지수",
    "제니",
    "로제",
    "리사",
  ],
  비비: ["비비", "BIBI", "김형서)"],
  비오: ["비비", "BEO", "유찬욱", "BE'O"],
  "상희(Sanghee)": ["상희", "Sanghee"],
  서리: ["서리", "Seori"],
  선미: ["선미", "Sunmi", "이선미"],
  선우정아: ["선우정아", "sunwoojunga"],
  손디아: ["손디아", "sondia"],
  "숀 (SHAUN)": ["숀", "SHAUN"],
  "수란 (SURAN)": ["수란", "SURAN"],
  "스테이씨 (STAYC)": ["스테이씨", "STAYC"],
  스텔라장: ["스텔라장", "Stella Jang", "스텔라장 (Stella Jang)"],
  심규선: ["심규선", "Sim Gyu-seon", "Lucia"],
  "쏠 (SOLE)": ["쏠", "SOLE"],
  "아이네(INE)": ["아이네", "INE"],
  아이들: [
    "아이들",
    "Idle",
    "I-dle",
    "(G)I-DLE",
    "우기",
    "민니",
    "미연",
    "예슈화",
    "전소연",
  ],
  "아이브 (IVE)": [
    "아이브",
    "IVE",
    "장원영",
    "이서",
    "레이",
    "리즈",
    "안유진",
    "가을",
  ],
  "아이브(IVE)": [
    "아이브",
    "IVE",
    "장원영",
    "이서",
    "레이",
    "리즈",
    "안유진",
    "가을",
  ],
  아이오아이: [
    "아이오아이",
    "IOI",
    "아이오아이 (IOI)",
    "김세정",
    "전소미",
    "청하",
    "주결경",
    "김소혜",
    "정채연",
    "최유정",
    "임나영",
    "김도연",
    "강미나",
    "연정",
  ],
  "아이유 (IU)": ["아이유", "IU", "이지은"],
  악동뮤지션: ["악동뮤지션", "AKMU", "악뮤"],
  안예은: ["안예은", "AHN YEEUN", "AHNYEEUN"],
  알리: ["알리", "ALI"],
  에일리: ["에일리", "Aliee"],
  엔플라잉: [
    "엔플라잉",
    "NFlying",
    "N.Flying",
    "이승협",
    "유회승",
    "차훈",
    "김재현",
    "서동성",
  ],
  예빛: ["예빛", "Yebit"],
  "우즈 (WOODZ)": ["우즈", "WOODZ", "조승연"],
  유성은: ["유성은", "U Sung Eun", "USungEun"],
  윤미래: ["윤미래", "Yoon MiRae", "윤미래 (Yoon Mi Rae)", "YoonMiRae"],
  윤하: ["윤하", "Youn Ha", "윤하 (Youn Ha)", "YounHa"],
  음율: ["음율", "UmYull"],
  "이마세 (imase)": ["이마세", "imase"],
  이문세: ["이문세", "leemoonsae", "Lee MoonSae"],
  이바다: ["이바다", "Lee ba da", "이바다 (Lee ba da)", "leebada"],
  이세계아이돌: [
    "이세계아이돌",
    "이세돌",
    "릴파",
    "주르르",
    "아이네",
    "비찬",
    "고세구",
    "징버거",
  ],
  이소라: ["이소라", "Lee sora", "Leesora"],
  이수영: ["이수영", "Lee Soo Young", "LeeSooYoung"],
  이예린: ["이예린", "Lee YeaLin", "LeeYeaLin"],
  이하이: ["이하이", "Lee Hi", "LeeHi"],
  이한울: ["이한울", "Lee HanUl", "LeeHanUl"],
  "자이언티 (Zion.T)": ["자이언티", "Zion.T", "Zion.t"],
  잔나비: ["잔나비", "Jannabi", "잔나비 (Jannabi)", "최정훈"],
  정승환: ["정승환", "Jung Seung Hwan", "JungSeungHwan"],
  정우: ["정우", "Jung Woo", "JungWoo"],
  정은지: ["정은지", "Jeong Eun Ji", "JeongEunJi"],
  정준일: ["정준일", "Jung Joo nil", "JungJooNil"],
  제니: ["제니", "Jennie", "JENNIE", "제니 (Jennie)"],
  제이레빗: ["제이레빗", "J Rabbit", "JRabbit", "J-Rabbit"],
  제이세라: ["제이세라", "J-Cera", "J cera", "Jcera"],
  "청하,슬기,신비,소연": ["청하", "슬기", "신비", "소연"],
  최에근: ["최에근", "YEGNY", "Choi Ye Gyeon", "ChoiYeGyeon"],
  "최예근 밴드": [
    "최예근 밴드",
    "최예근",
    "Choi ye_guen Band",
    "ChoiYeGeunBand",
  ],
  "츠키 (tuki)": ["츠키", "tuki"],
  카더가든: [
    "카더가든",
    "Car, The Garden",
    "Car The Garden",
    "CarTheGarden",
    "차정원",
  ],
  케이시: ["케이시", "Kassy"],
  "크러쉬(Crush)": ["크러쉬", "Crush", "신효섭", "크러시"],
  크림스나: ["크림스나", "Crimsona"],
  탑현: ["탑현", "Top Hyun", "TopHyun"],
  태양: ["태양", "Taeyang", "TaeYang", "동영배"],
  태연: ["태연", "Taeyeon", "Taeyeon (태연)"],
  트와이스: [
    "트와이스",
    "TWICE",
    "트와이스 (TWICE)",
    "쯔위",
    "사나",
    "채영",
    "모모",
    "나연",
    "지효",
    "정연",
    "미나",
    "다현",
  ],
  프라이머리: ["프라이머리", "Primary", "Primary (프라이머리)"],
  "프레디 머큐리": ["프레디 머큐리", "Freddie Mercury"],
  하진: ["하진", "Ha Jin", "HaJin"],
  헤비: ["헤비", "hebi"],
  헤이즈: ["헤이즈", "Heize", "Heize (헤이즈)"],
  "헤이즈,Dean": ["헤이즈", "Dean", "헤이즈,Dean"],
  혁오: ["혁오", "HYUKOH", "혁오 (HYUKOH)", "HYUK OH"],
  황가람: ["황가람", "Hwang kaRam", "HwangkaRam"],
  "Adam Levine": ["Adam Levine", "애덤 르빈", "아담 르빈"],
  Adele: ["Adele", "아델"],
  Ado: ["Ado", "아도", "あど"],
  "Alexander Jean": ["Alexander Jean", "알렉산더 진", "앨렉산더 진"],
  "Anne-Marie": ["Anne-Marie", "안 마리", "안마리", "앤 마리", "앤마리"],
  "Ariana Grande, Justin Bieber": [
    "Ariana Grande",
    "Justin Bieber",
    "아리아나 그란데",
    "저스틴 비버",
    "아리아",
  ],
  Bahari: ["Bahari", "바하리", "루비 카", "나탈리아 판자렐라"],
  "Benson Boone": ["Benson Boone", "벤슨 분"],
  "BIG NAUGHTY": ["BIG NAUGHTY", "빅나티"],
  BTS: ["BTS", "방탄소년단", "정국", "뷔", "지민", "슈가", "rm", "진"],
  "BURNOUT SYNDROMES": [
    "BURNOUT SYNDROMES",
    "번아웃 신드롬즈",
    "번아웃신드롬즈",
  ],
  "Camila Cabello": ["Camila Cabello", "카밀라 카베요", "카밀라카베요"],
  "Charlie Puth": ["Charlie Puth", "찰리 푸스", "찰리푸스"],
  Christopher: ["Christopher", "크리스토퍼"],
  "Corinne Bailey Rae / Dua Lipa": [
    "Corinne Bailey Rae",
    "Dua Lipa",
    "커린 베일리 레이",
    "두아 리파",
    "커린베일리레이",
    "두아리파",
  ],
  Dean: ["Dean", "딘"],
  "Ed Sheeran": [
    "Ed Sheeran",
    "에드 시런",
    "에드 쉬런",
    "에드시런",
    "에드쉬런",
  ],
  "Ellie Goulding": ["Ellie Goulding", "엘리 굴딩"],
  "Fall Out Boy": ["Fall Out Boy", "폴 아웃 보이", "폴아웃보이"],
  "Frank Sinatra": ["Frank Sinatra", "프랭크 시나트라", "프랭크시나트라"],
  GD: ["GD", "G-DRAGON", "지드래곤", "권지용"],
  HANA: ["HANA", "하나"],
  HoneyWorks: ["HoneyWorks", "허니웍스", "HoneyWorkS"],
  "Idina Menzel": ["Idina Menzel", "이디나 멘젤", "이디나멘젤"],
  "Imagine Dragons": [
    "Imagine Dragons",
    "이매진 드래곤즈",
    "이매진드래곤즈",
    "이매진드래곤",
  ],
  issey: ["issey", "이세이"],
  "Jason Mraz": ["Jason Mraz", "제이슨 므라즈", "제이슨므라즈"],
  "Justin Bieber": ["Justin Bieber", "저스틴 비버", "저스틴비버"],
  "Keala Settle": [
    "Keala Settle",
    "키알라 세틀",
    "키알라세틀",
    "케알라 세틀",
    "케알라세틀",
  ],
  Loote: ["Loote", "루트"],
  Marcy: ["Marcy", "마루시", "マルシィ"],
  Maroon5: ["Maroon5", "마룬파이브", "마룬 파이브", "마룬5"],
  "Martin Garrix,Bebe Rexha": [
    "Martin Garrix",
    "Bebe Rexha",
    "마틴 게릭스",
    "마틴게릭스",
    "비비 렉사",
    "비비렉사",
  ],
  "Olivia Rodrigo": ["Olivia Rodrigo", "올리비아 로드리고", "올리비아로드리고"],
  QWER: [
    "QWER",
    "큐떱",
    "큐떠블유이알",
    "큐더블유이알",
    "쵸단",
    "마젠타",
    "히나",
    "시연",
  ],
  RADWIMPS: ["RADWIMPS", "래드윔프스", "ラッドウィンプス", "랏도"],
  "Richard Sanderson": ["Richard Sanderson", "리처드 샌더슨", "리처드샌더슨"],
  "Sam Smith": ["Sam Smith", "샘 스미스", "샘스미스", "샘"],
  "Sasha Alex Sloan": ["Sasha Alex Sloan", "샤샤 슬론", "샤샤슬론"],
  "Selena Gomez": ["Selena Gomez", "셀레나 고메즈", "셀레나고메즈", "셀레나"],
  "Shawn Mendes": ["Shawn Mendes", "숀 멘데스", "숀멘데스"],
  "SHY Martin": ["SHY Martin", "샤이 마틴", "샤이마틴"],
  Sia: ["Sia", "시아"],
  SIA: ["SIA", "시아"],
  "Tate McRae": ["Tate McRae", "테이트 맥레이", "테이트맥레이"],
  "Taylor Swift": ["Taylor Swift", "테일러 스위프트", "테일러스위프트"],
  "The Chainsmokers": ["The Chainsmokers", "체인스모커스", "체인스모커스"],
  "The Weeknd": ["The Weeknd", "위켄드"],
  "Tones and I": ["Tones and I", "톤즈 앤 아이", "톤즈앤아이"],
};
